### ISSUE TITLE
"No such file or directory" error when searching Test_data 

### ISSUE THREAD

**Issue by eselimnl** [zstephens/exogene#2]
Hi Stephen, I am not experienced Docker user and couldn't solve the issue by myself. I am running Docker on WSL (Cygwin and Ubuntu). After running exogene in Docker, I use this command as you described:
`./Exogene-SR.sh -f1 test_data/SRR3104446_1.fq.gz -f2 test_data/SRR3104446_2.fq.gz -r refs/HumanViral_Reference_12-12-2018.fa -o output`

Even though the path is true, gzip can't open or read the files:

> gzip: test_data/SRR3104446_1.fq.gz: No such file or directory
> gzip: test_data/SRR3104446_2.fq.gz: No such file or directory
> [M::bwa_idx_load_from_disk] read 0 ALT contigs
> [main] Version: 0.7.17-r1188
> [main] CMD: /usr/bin/bwa mem -k 30 -t 4 /home/refs/HumanViral_Reference_12-12-2018.fa -
> [main] Real time: 0.018 sec; CPU: 0.020 sec
> Traceback (most recent call last):
>   File "/home/exogene/dev/readlist_2_fq.py", line 38, in <module>
>     fi_1 = get_file_handle(IN_R1, 'r')
>   File "/home/exogene/dev/readlist_2_fq.py", line 17, in get_file_handle
>     return open(fn, rw)
> IOError: [Errno 2] No such file or directory: 'test_data/SRR3104446_1.fq'
> [bam_header_read] EOF marker is absent. The input is probably truncated.
> [bam_header_read] EOF marker is absent. The input is probably truncated.
> We were unable to grab template length stats from bwa.log, making a complete guess...
> estimated template length: 350 50
> === BREAKPOINT DEVIATIONS:
> 
> CHR     INTEGRATION_POS #READS  VIRUS   ANNOTATION      SOFTCLIP_POS    #SOFTCLIP           D
> ISCORDANT_POS   #DISCORDANT     LONGREAD_POS    #LONGREAD       NEAREST_GENE
> 
> mv: cannot stat '*_hits.ids': No such file or directory

Thank you for your time.

**Comment by SebastianS-1997** [comment]
Hi, It seems that this is how it should be done.
docker run -it -v ${HOME}:${HOME} zstephens/exogene:v15
cd home
(base) root@a07eef7e2214:/home# ./Exogene-SR.sh -f1 /home/test_data/SRR3104446_1.fq.gz -f2 /home/test_data/SRR3104446_2.fq.gz -r /home/your/path/hg38_plus_viral.fa.sa -o /home/your/path/OUT/
